import { AblyClientProvider } from "@/components/ably-provider";
import { ConvexClientProvider } from "@/components/convex-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ably Spaces",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          {/* <AblyClientProvider> */}
            <EdgeStoreProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
                storageKey="Mosiac-theme-2"
              >
                <Toaster position="bottom-center" />
                {children}
              </ThemeProvider>
            </EdgeStoreProvider>
          {/* </AblyClientProvider> */}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
